<?php

namespace Tests\Stubs;

use App\Models\Product\MyProduct;
use App\Models\Shopify\Shop;
use App\Services\ShopifyService;

class FakeShopifyService extends ShopifyService
{
    public function exportProduct(MyProduct $product): int
    {
        [$productData, $optImages] = $this->prepare($product);

        return $product->id;
    }

    public function setClient(Shop $shop): ShopifyService
    {
        //parent::setClient($shop); // TODO: Change the autogenerated stub
        return $this;
    }

    public function webhook(array $hook): array
    {
        return optional($this->client); // TODO: Change the autogenerated stub
    }

    /**
     * @param MyProduct $myProduct
     */
    public function updateProduct(MyProduct $myProduct): int
    {
        return $myProduct->id;
    }
}
